### ISSUE TITLE
useService logs warning about uninitialized service when service is passed to child component

### ISSUE THREAD

**Issue by kevinold** [davidkpiano/xstate#1132] opened 2020-04-16 22:16 UTC
**Description**
In v4.7.0-4.9.0 a warning is logged to the console when calling `useService` on a service prop.

**Expected Result**
No warning.

**Actual Result**
Warning: Attempted to read initial state from uninitialized service 'toggle'. Make sure the service is started first.

**Reproduction**
https://codesandbox.io/s/xstate-react-template-uninitialized-service-warning-cz351

**Additional context**
Note that the machine is created at the top of the application (App) and passed to a child (Child).

**Comment by davidkpiano** [comment] 2020-04-16 23:04
This behavior likely occurred in 4.8.x as well, can you check there?

**Comment by kevinold** [comment] 2020-04-17 00:05
@davidkpiano Yes, checked all the way back to 4.7.0 where this issue begins. It was not present 4.6.7 and 4.7.0 RC's throw errors.

**Comment by seloner** [comment] 2020-05-19 17:04
@davidkpiano Is any work around for that ?   I am trying to put the service in React Context and consume it after but I am getting the same error .

**Comment by davidkpiano** [comment] 2020-05-19 18:55
Try updating to the latest `xstate` and `@xstate/react@next`; the warning is no longer there.

**Comment by seloner** [comment] 2020-05-19 19:33
@davidkpiano  I am on "@xstate/react": "^0.8.1", and "xstate": "^4.9.1" and I am still getting the warning . The useService is returning undefined  so I can not use the machine .

**Comment by davidkpiano** [comment] 2020-05-19 23:35
Does the app otherwise work fine? If so, you can ignore the warning for now.

**Comment by seloner** [comment] 2020-05-20 06:03
@davidkpiano 
It is not wokring. I am getting undefined in the useService Hook and not only on mount.It does not change.
![image](https://user-images.githubusercontent.com/29483115/82410015-ac41ca80-9a77-11ea-9cd8-8381b0bcf021.png)
![image](https://user-images.githubusercontent.com/29483115/82410363-646f7300-9a78-11ea-826e-9e52e2a9a3c8.png)

My workaround is to pass into React context, [state,send] from UseMachine instead of the service . I can provide a code sandbox if you want.

**Comment by seloner** [comment] 2020-05-21 17:45
@davidkpiano in @xstate/react/v/1.0.0-rc.4 I have no problem . Is it safe to use the next version for production ?

**Comment by seloner** [comment] 2020-05-25 16:03
@davidkpiano 
In versions after 1.0.0-rc.1 when you try to put initial context in the Machine like the example in docs 
https://xstate.js.org/docs/guides/context.html#initial-context I am getting this warning 

Machine given to `useMachine` has changed between renders. This is not supported and might lead to unexpected results.
Please make sure that you pass the same Machine as argument each time.

In versions before  1.0.0-rc.2 I am getting the service warning .

Sandbox : https://codesandbox.io/s/great-herschel-9opwh?file=/src/App.js

I guess its just a warning a not a bug ?

**Comment by davidkpiano** [comment] 2020-05-25 16:19
@seloner Prefer this:

```js
  const [state, send] = useMachine(counterMachine, {
    context: someContext // initial context
  });
```

**Comment by Andarist** [comment] 2020-05-25 21:16
@seloner the problem is that `useMachine` can only ever work with the same instance of a machine. Machines need to have static config - and it's not possible to change this for a particular `useMachine` call. The warning exists to avoid confusion that you could actually provide a different argument there - and as you are calling `withContext` each render it creates a new Machine each render and we can't recognize them being the same between renders so it's up to you to memoize it correctly or use @davidkpiano's suggestion

**Comment by seloner** [comment] 2020-05-27 17:09
@Andarist I want to persist state also. I am getting no warning ,I guess its ok to do it like that ?  
![image](https://user-images.githubusercontent.com/29483115/83050891-de45c480-a055-11ea-955c-31afbce138cc.png)

**Comment by davidkpiano** [comment] 2020-07-25 15:44
This is now fixed in the latest `@xstate/react` RC.

**Closed by davidkpiano** 2020-07-25 15:44 UTC
Labels: bug, ⚛︎ @xstate/react
