### ISSUE TITLE
Visualizer won't show child machine

### ISSUE THREAD

**Issue by tomByrer** [davidkpiano/xstate#1574] opened 2020-10-20 05:31 UTC
**Description**
Visualizer won't show child machine

**Actual Result**
![image](https://user-images.githubusercontent.com/1308419/96544136-91b08f00-126b-11eb-8930-7a4eb502af9d.png)

**Reproduction**
https://xstate.js.org/viz/?gist=592b79fd90a15f58acd14bddc1682725
Same thing in Inspector.

**Additional context**
Current (online).

(I did an issue search & didn't find anything.)
Thanks!

**Comment by davidkpiano** [comment] 2020-10-20 14:06
Please use the [XState inspector (CodeSandbox template)](https://codesandbox.io/s/xstate-viz-template-f3dtr) instead.

More info: statecharts.io

**Comment by tomByrer** [comment] 2020-10-20 20:46
Sure, but it gives the exact same output; that's why I assume they use same engine.

https://codesandbox.io/s/xstate-inspect-no-child-o4dps

**Comment by saltzm** [comment] 2020-10-20 22:20
Oh - I think the issue in the sandbox might be that you have to use the dropdown on the right hand side to switch what machine it's currently displaying. I was having trouble figuring that out too (which is how I found this issue). I expected to be able to click to expand or something along those lines. As far as I can tell there's no way to see both levels of the hierarchy at the same time. For the record the https://xstate.js.org/viz tool is much simpler to use and it would be cool for it to be fully featured but I understand if you don't want to support both, especially if users of this are supposed to eventually get their own local visualization setup going.

**Comment by davidkpiano** [comment] 2020-10-20 22:33
> For the record the xstate.js.org/viz tool is much simpler to use and it would be cool for it to be fully featured

In which ways is it simpler? I'd appreciate the feedback.

**Comment by saltzm** [comment] 2020-10-20 23:25
I'm just starting to use the tool as of yesterday (which I'm very excited about, by the way, it's super cool), and it's just a clean place to go paste the stuff I'm working on, click update, and see how it looks.

With the inspect sandbox, I had a few issues (keep in mind I've never used codesandbox before):
1. I somehow got myself in a state where it popped open a new tab for the sandbox.io/inspect diagram rather than doing it in the same tab, and then every time I would type anything it would decide to update it and then transfer me to that tab. Including when I turned off autosave.
2. In the state machine I was playing with when I pasted it in, I had it set up so that it wouldn't terminate (on accident) and would just keep transitioning over and over again, which generated more and more state diagrams. I couldn't figure out how to just generate a static visualization of the state machine without actually running it, which the xstate.js.org/viz tool does. I think visualizing the behavior at runtime is a super cool feature but it's not helpful if all I want is to look at a mostly static view and maybe interact with it manually.
3. I had some time delay transitions and the inspect tool seemed to have its own idea of what time was (in other words, it would not delay at all). (That's true on the viz tool as well I think.)
4. I'm not developing anything for web and I'm doing the actual development locally in vim and just running it with node in the terminal to see the console output. It was kind of unclear to me if it's possible to use inspect locally and what the magical URL you pass to the inspect flag does or how that works. The best thing for me would really be if I could just run some command in javascript that would dump some static format that I could open up without having a full web app. But absent that, the viz tool is pretty nifty.

Thanks! Hope that helps.

**Comment by tomByrer** [comment] 2020-10-21 00:32
> use the dropdown on the right hand side to switch what machine it's currently displaying

I did not see that before, thanks for pointing the dropdown out!  That does 'work', but I was expecting how the sub-states look.  I updated the 1st post for my expectation.

**Comment by saltzm** [comment] 2020-10-21 03:22
Glad that helped!
 
Also about my previous reply, I apologize but now that I'm looking again when I'm not rushing to figure things out, I see I had a lot of things wrong:
1. That happens with the sandbox you linked, @davidkpiano, but not the one @tomByrer linked. I think it's that @tomByrer used `iframe: () => document.querySelector("iframe[data-xstate]")` instead of the url option.
2. I noticed the viz tool does actually do the same thing, it just doesn't let you see the visualizations at previous points in time.
3. The time delay actually works fine (insert embarrassed emoji here). I just got overwhelmed at the rapidly growing dropdown list, I guess.
4. Again, now that I'm just looking and not in a rush I see that it should be quite easy to use this locally. I still would like to be able to generate static diagrams somehow if possible. If there are docs on inspect I'm missing feel free to point me to them.

Sorry for all the noise.

**Comment by tomByrer** [comment] 2020-10-21 07:52
>     4\. generate static diagrams

Screenshot?

**Comment by saltzm** [comment] 2020-10-22 18:21
I could take screenshots, but then I have to step through all the machines manually, make sure all the states where submachines are generated are encountered, etc. It seems doable to dump out the graph without having to actually run the service, which would be useful just to explore the overall architecture. But maybe the Creator tool that's planned will allow more of a view like that. Anyway, this is off topic from your main issue at this point.

**Comment by thewtex** [comment] 2020-10-29 01:47
I am also not observing the child machines:

![image](https://user-images.githubusercontent.com/25432/97514904-3d419980-1966-11eb-9a77-461ba8122b37.png)

Is statecharts.io open source? It has the error:

> inspect.js:1 Uncaught TypeError: Cannot use 'in' operator to search for 'type' in 
    at o (inspect.js:1)

but I do not know if it is related.

The issue can be reproduced with:

```
git clone https://github.com/thewtex/itk-vtk-viewer 
cd itk-vtk-viewer
git checkout 320f8d6a4c63315a9555ec45a21bbccdcba20e76
npm install
npm run build
npm start
```

**Comment by davidkpiano** [comment] 2020-10-29 04:58
Are you using the latest version of XState?

**Comment by thewtex** [comment] 2020-10-29 14:04
@davidkpiano yes, using the latest released xstate version `4.13.0`.

**Comment by davidkpiano** [comment] 2021-01-22 03:43
This should be fixed with the latest version of `@xstate/inspect`.

Please make a CodeSandbox reproduction if it is not.

**Closed by davidkpiano** 2021-01-22 03:43 UTC
Labels: 🔎 @xstate/inspect

**Comment by thewtex** [comment] 2021-01-28 00:21
@davidkpiano thank you!

**Comment by hefeizz** [comment] 2021-02-19 03:54
@davidkpiano hi, I use xstate@4.16.2 with @xtate/inspect@0.4.1, and the states of child machine doesn't show in the chart. Is this by design that states of a child machine doesn't show in the chart? 

codesandbox: https://codesandbox.io/s/xstate-inspect-no-child-forked-p2xte

`child.step1`, `child.step2` and `child.step3` doesn't show in the snapshot.

![image](https://user-images.githubusercontent.com/3992113/108455274-e52dfa80-72a8-11eb-850e-a914f4faa3fe.png)

**Comment by davidkpiano** [comment] 2021-02-19 04:00
@hefeizz Click here:

<img width="384" alt="CleanShot 2021-02-18 at 22 59 55@2x" src="https://user-images.githubusercontent.com/1093738/108455878-0eb13c80-723d-11eb-8ae5-290ce4c718bf.png">

**Comment by hefeizz** [comment] 2021-02-19 06:23
@davidkpiano thank you!
