### ISSUE TITLE
Typescript declaration gives me wrong type in onDone action.

### ISSUE THREAD

**Issue by erizet** [davidkpiano/xstate#449] opened 2019-05-07 06:35 UTC
I don't know if this is a bug or something I've misunderstood.

I try to implement the fetch machine sample from the documentation, but I try to use Typescript. Now I've run into the following problem. I have declared my 'loading' state as the following.

```
        loading: {
            invoke: {
                src: 'fetchData',
                onDone: {
                    target: 'success',
                    actions: actions.assign<FetchContext, FetchEvent>({
                        result: (_, e) => {
                            return (e as any).data;
                        }
                      })
                } as TransitionConfig<FetchContext, DoneInvokeEvent<any>>,
                onError: {
                    target: 'failure.communicationError'
                }
            }
        },

```

Under 'actions' the variable 'e' is not of type FetchEvent. Actually the 'e.type' is not any of the values I've declared in my FetchEvent. It's 'done.invoke.fetchData'. Is there a way to fix this so the TS declarations matches the runtime types?

**Comment by assuncaocharles** [comment] 2019-09-09 17:28
Hi @erizet 

Tried to reproduce this one but didn't get any error

<img width="736" alt="Screen Shot 2019-09-09 at 19 22 36" src="https://user-images.githubusercontent.com/8545105/64552377-6f91d100-d337-11e9-817d-813ffe603d69.png">

**Comment by abhi18av** [comment] 2019-11-17 09:07
Hmm, interesting. It seems that perhaps the upgrades to `Typescript` or `XState` might have resolved this issue already. Would be nice if @erizet  could shed more light on this.

**Comment by Andarist** [comment] 2019-11-17 10:33
OP has not responded since @assuncaocharles's response. I assume this works now as expected and going to close this issue. 

If you provide a repro case for a broken behavior then please post it here and I'll reopen or just create a new issue. Thanks for understanding.

**Closed by Andarist** 2019-11-17 10:33 UTC
Labels: typescript

**Comment by abhi18av** [comment] 2019-11-17 10:41
Yeah, after some experimentation I also couldn't reproduce this as well. I agree, better to close this 👍
