### ISSUE TITLE
Error propagation from actions execution using interpreter

### ISSUE THREAD

**Issue by alizbazar** [davidkpiano/xstate#463] opened 2019-05-20 19:22 UTC
## Bug or feature request?
Feature request / question.

## Description:
Using the interpreter, sometimes there are situations where an action results in synchronous runtime error. In these cases the error is not displayed and is fully "swallowed" by the state machine / interpreter while blocking the machine from executing the transition (think of, for example, error occurring in `onEntry` action).

Such errors are incredibly hard do debug as everything seems to work - except for the machine not going forward.

**How should error handling of actions / services / activities be done?**

## (Bug) Expected result:
Interpreter should have a mechanism for errors to be caught / propagate outside, or at least be logging them in a clear manner.

**Comment by davidkpiano** [comment] 2019-05-21 01:34
Can you make a [CodeSandbox](https://codesandbox.io) example?

**Comment by alizbazar** [comment] 2019-05-21 06:36
Here's a simplified example using [XState Viz](https://statecharts.github.io/xstate-viz/):

```js
const notifyConnected = (...args) => console.log(...args)
const connect = () => Promise.resolve()

const machine = Machine({
  initial: 'connecting',
  // context: {},
  states: {
    connecting: {
      invoke: {
        src: 'connect',
        onDone: 'connected',
      },
    },
    connected: {
      id: 'connected',
      onEntry: 'notifyConnected',
    },
  },
}, {
  actions: {
    notifyConnected: ctx => {
      notifyConnected(ctx.id)
    },
  },
  services: {
    connect: () => connect(),
  },
})
```

If you open the console, you see that nothing exceptional has happened. There is no sign of failure. However, there was "Uncaught TypeError: Cannot read property 'id' of undefined" error that propagated from the action execution and broke the transition.

The issue in this case is accessing `ctx.id` in the action. So if you bring back `context: {}`, the error is "fixed" and machine successfully transitions to "connected".

Interestingly enough, if you replace the `connect` service with a custom event, the error gets thrown from `StateChart.send` correctly. Example:

```js
const notifyConnected = (...args) => console.log(...args)

const machine = Machine({
  initial: 'connecting',
  // context: {},
  states: {
    connecting: {
      on: {
        CONNECTED: 'connected',
      },
    },
    connected: {
      id: 'connected',
      onEntry: 'notifyConnected',
    },
  },
}, {
  actions: {
    notifyConnected: ctx => {
      notifyConnected(ctx.id)
    },
  },
  services: {
    connect: () => connect(),
  },
})
```

It seems that with services, there is no one to communicate the error back to - so it gets swallowed. 

Should there be a **global error subscription / emitter** for such cases, or how should one make sure such errors get noticed?

**Comment by alizbazar** [comment] 2019-05-21 09:07
Interestingly, if using `after: 1000` for the transition, the error gets thrown correctly.

**Comment by Andarist** [comment] 2019-07-15 20:43
The good thing is that with new versions of XState this error wouldn't get swallowed - https://codesandbox.io/s/restless-tree-x2o1c . However, to be SCXML-compliant we should catch it and wrap it to be an event of `error.execution` type - which could be handled or ignored (swallowed). With `strict` option we could fail loudly on unhandled errors.

**Comment by alizbazar** [comment] 2019-07-21 18:43
Should every xstate machine always listen to `error.execution` event to catch possible errors?

**Comment by Andarist** [comment] 2019-07-22 06:48
That's a good question. I think that currently no `error.execution` is being sent - we use `error.platform.<suffix>` which allows us for scoping errors per state/invocations (`error.execution` is kinda "global" as per SCXML spec). However, there are cases when we actually should send `error.execution` - i.e. when an error happens when invoking a guard.

**Comment by alizbazar** [comment] 2019-07-23 10:12
Just pragmatically thinking here: the downside of global events like such is that they add extra complexity to the statechart logic. What I like about statecharts is that they encapsulate the whole business logic really nicely without much overhead or extra boilerplate.

If we start sending global `error.execution` event, every time we will need to write some custom logic for listening to the events and acting upon them - i.e. firing some action, moving into "restarting" state etc. If the logic is not included in the state chart, we just miss these exceptions ever happening. I think majority of the users will forget writing handling for `error.execution` and will be struggling with difficult to debug bugs (swallowed errors).

-> Could we instead make some "hard to fail" solution for majority of users, while having more advanced SCXML spec-like logic as on opt-in?

**Comment by Andarist** [comment] 2019-07-23 11:49
> -> Could we instead make some "hard to fail" solution for majority of users, while having more advanced SCXML spec-like logic as on opt-in?

What do you mean exactly?

Errors shouldn't be completely swallowed - that's for sure. If you know in which scenario they can be swallowed please let us know. For now, we can only log them though - anything else would be a breaking change. However in the future (next major) IMHO we should consider failing the whole machine on uncaught errors.

**Comment by alizbazar** [comment] 2019-07-23 12:57
I mean that if to notice an error one needs to write logic to handle `error.execution` event, that's easy to miss and can result in mysterious bugs. However, I tested the above code in your Codesandbox and an unhandled Promise rejection was indeed logged in browser console.

Logging is great! I'm just thinking that in any real production application (mobile, web) uncaught errors are usually funneled to some logging platform such as BugSnag etc. If error occurs only in production, sometimes that's the only way to notice an issue. I wonder how this should be done here.

**Comment by Andarist** [comment] 2019-07-23 13:24
If everything is properly logged then it should be easy to send this to bug-collecting services. Wondering if there is anything else to do/discuss here or maybe we could close this issue?

**Comment by alizbazar** [comment] 2019-07-23 19:25
Sounds good to me 👌

**Comment by sukima** [comment] 2020-02-17 03:59
@alizbazar Could you expand on how this is a closed discussion? I've red ever conversation in here and I was unable to discover a resolution/consensus.

I can produce with the latest XState V4 (in production today!) with https://xstate.js.org/viz/?gist=3b570a34ea938bd5a7f6692e11272bad

```js
  const fetchMachine = Machine({
    id: 'fetch',
    initial: 'idle',
    states: {
      idle: {
        on: {
          FETCH: 'loading'
        }
      },
      loading: {
        invoke: {
          src: 'test',
          onDone: 'success'
        }
      },
      success: {
        type: 'final'
      }
    }
  }, {
    services: {
      test: () => {
        return Promise.reject(new Error('bork'));
      }
    }
  });
```

There are no unhanded exceptions in the console (FF 73, Chrome 80). How would one make sure that a rejected service (either via an actual exception or a syntax/runtime error) is indeed *not* swallowed?!

**Comment by sukima** [comment] 2020-02-17 04:04
This can be further complicated if an onError/action throws an exception resulting in an undefined react error: https://xstate.js.org/viz/?gist=efb5e501a585bf7533d1122117209b5a

**Comment by qtiki** [comment] 2020-03-27 11:21
> Logging is great! I'm just thinking that in any real production application (mobile, web) uncaught errors are usually funneled to some logging platform such as BugSnag etc. If error occurs only in production, sometimes that's the only way to notice an issue. I wonder how this should be done here.

I just found my way here because I was trying to figure out why we don't get a proper sentry.io error from a service that fails in strict mode. Turns out that the error is just logged to console and not propagated to Sentry's unhandled promise rejection handler. While logging is great for backend applications this happens in frontend code where we rely on Sentry error collection as it groups the errors based on callstack and other values.

As a side note the error logging does not respect source maps in Chrome as it's concatenating a string like `console.log("Error: " + error)`. The error should be sent to the logger as an error object to allow Chrome to handle sourcemaps, ie. `console.log("Error:", error)`.

**Comment by davydof** [comment] 2020-10-30 05:06
hello @davidkpiano :)

do xstate has a solution to handle an exception from actions?
https://xstate.js.org/viz/?gist=f81794200093641f49da5a23987cfc32

**Comment by davidkpiano** [comment] 2021-06-21 03:42
Closing this because the original issue (sync errors in actions) is now working as expected (errors are thrown, not swallowed).

#2319 will be used to address the source map + unhandled promise rejection issue.

**Closed by davidkpiano** 2021-06-21 03:42 UTC
Labels: enhancement

**Comment by ahamid** [comment] 2021-12-29 22:22
I am still seeing the synchronous exception swallowing behavior with 4.26.1 per @davydof's example. Should I be trying to catch an `xstate.error` or `error.execution` event? (I don't think any are being emitted)

**Comment by davidkpiano** [comment] 2021-12-30 13:24
> I am still seeing the synchronous exception swallowing behavior with 4.26.1 per @davydof's example. Should I be trying to catch an `xstate.error` or `error.execution` event? (I don't think any are being emitted) When the action is invoked via an automatic transition (instead of an explicit client `.send` call; e.g. an 'entry' action), there is no way to catch it at the point of invocation.

Can you please open a new issue with a reproduction?

**Comment by ahamid** [comment] 2022-01-20 21:17
> Can you please open a new issue with a reproduction?

#2954
