### ISSUE TITLE
Targetless transition on parent state changes state

### ISSUE THREAD

**Issue by avaragado** [davidkpiano/xstate#644] opened 2019-09-02 09:34 UTC
## To reproduce

1. https://xstate.js.org/viz/?gist=887f4c842224a6d1ff0a253548d68b47
2. Click NEXT to move to state bbb
3. Click TEST

## (Bug) Expected result:

Machine stays in state bbb

## (Bug) Actual result:

Machine transitions to state aaa

## Use case

I'd like to have top-level actions that modify context without changing the current state.

**Comment by Andarist** [comment] 2019-09-02 11:26
I can confirm that this seems broken in XState 4.6, but seems to be fixed i 4.7 (currently at RC stage) - https://codesandbox.io/s/wizardly-lamarr-eo00y

**Comment by johnyanarella** [comment] 2019-09-03 18:08
Updated some older code from XState 4.4 to 4.6 today and got burned by this one, too.

**Comment by tivac** [comment] 2019-09-03 18:19
This looks an awful lot like #507 (which was fixed in #545 but hasn't been released yet).

**Comment by davidkpiano** [comment] 2019-09-03 19:54
Try it out with `xstate@next` please 🙏 This issue should be resolved.

**Comment by davidkpiano** [comment] 2019-10-19 18:06
Closing as this is resolved in `xstate@next`

**Closed by davidkpiano** 2019-10-19 18:06 UTC
