### ISSUE TITLE
Noticing an action running at incorrect times (on `entry` and on `sendParent`)

### ISSUE THREAD

**Issue by dougmacklin** [davidkpiano/xstate#872] opened 2019-12-13 18:25 UTC
**Description**
Say I have a machine that runs an action in a transient state before transitioning, like so:

```
initial: "initializing",
states: {
  initializing: {
    entry: "initialize",
    on: {
      "": "editing"
    }
  },
  editing: {}
}
```

I noticed that if this action uses `assign`, it runs three times ([code sandbox](https://codesandbox.io/s/action-with-assign-runs-multiple-times-ysmgt)).

In that sandbox demo, the additional action that doesn't use `assign` only runs once. Is this expected? If I drop down to version 4.5, it looks like it only runs two times instead of three.

On a related note, if I expand the example above to include a child machine that uses `sendParent` to communicate, the `initialize` action runs again, despite it not being called whatsoever as we are in the `editing` state and do not reenter `initializing` ([code sandbox](https://codesandbox.io/s/action-in-different-state-runs-in-sendparent-9pydt)).

**Expected Result**
The `initialize` action runs once on `entry` when the machine starts up and never from `sendParent`.

**Actual Result**
The `initialize` action runs three times on `entry` when the machine starts up and once every time from `sendParent`.

**Reproduction**
- on `entry`: https://codesandbox.io/s/action-with-assign-runs-multiple-times-ysmgt
- on `sendParent`: https://codesandbox.io/s/action-in-different-state-runs-in-sendparent-9pydt

**Additional context**
In my real-world use-case, I'm spawning a number of child machines during the `initialize` action. Having this run repeatedly during every `sendParent` is causing a noticeable slowdown.

**Comment by Andarist** [comment] 2019-12-13 23:00
> I noticed that if this action uses assign, it runs three times (code sandbox).

Please see https://github.com/davidkpiano/xstate/issues/838#issuecomment-564783742

As to the other problem with `sendParent` - it's basically the very same problem. Currently `.initialState` is read with each render.

Because this is a duplicate of #838 - I'm going to close this.

**Closed by Andarist** 2019-12-13 23:00 UTC
Labels: bug
