### ISSUE TITLE
Restoring services

### ISSUE THREAD

**Issue by timoxley** [davidkpiano/xstate#332] opened 2019-01-26 18:28 UTC
## Probable Bug

Is there a way to re-invoke a service when starting from an initialState with an invoked service?
It seems to work ok so long as the service didn't dispatch any events
but if the service dispatches an event, then it'll never start back up, nor will any activities or actions fire

e.g. https://codesandbox.io/s/53qpm2nr4p

Two saved states at the bottom there. If starting from "withDispatch", (i.e. saved after service dispatched an event) the service will never start.
if saved before it sent the event, "withoutDispatch", i.e. removing the dispatch in the service, then it'll start just fine.

**Comment by davidkpiano** [comment] 2019-01-26 18:54
This might be a duplicate of https://github.com/davidkpiano/xstate/issues/307

**Closed** 2019-10-22 03:47 UTC
Labels: documentation
