### ISSUE TITLE
The visualizer breaks on JSON.stringify calls when there are circular references in machine definition

### ISSUE THREAD

**Issue by dmitrynovik** [davidkpiano/xstate#1497] opened 2020-09-30 04:00 UTC
**Description**
Quite often we have a hierarchy of state machines (e.g. parent-child relationship) where by the nature of definition there are circular references. In such cases, the call to `JSON.stringify` throws an error. 

**Expected Result**
The visualizer is able to visualize parent-child state machine relationship.

**Actual Result**
An error

**Suggestion**
Replace the `JSON.stringify` calls with a safe alternative e.g. [fast-safe-stringify](https://www.npmjs.com/package/fast-safe-stringify)

**Comment by Andarist** [comment] 2020-09-30 14:42
Could you showcase how have you created a circular reference between parent and a child in their definitions?

**Comment by Blacktiger** [comment] 2020-10-01 19:32
Make sure to look at #1151 @Andarist. I'm unsure if we're seeing the same issue but I believe this might be related to service.machine being a different object after initialization?

**Comment by dmitrynovik** [comment] 2020-10-02 07:22
> Could you showcase how have you created a circular reference between parent and a child in their definitions?

Guess what, the `xstate` update to `4.13.0` did solve my particular issue (well done, guys!), but there could be others like the one opened by @Blacktiger . You still need to remember that the `JSON.stringify(whatever)` is inherently unsafe and will throw an error once a cycle is detected, and there could be probably 1 000 000 ways to create a cycle in an object graph ...

**Comment by Andarist** [comment] 2020-10-02 13:50
I understand that the `JSON.stringify` is unsafe when it comes to cycles but to solve this properly I really feel that we'd have to get a valid repro case first. It seems quite unusual to me at this point to get into a situation with cycles when usually you just write configs inline and I'm not sure what part of the schema could reference another one? I understand that you had to land somehow in such a situation but it would be of great help if I would understand how.

**Comment by davidkpiano** [comment] 2020-10-02 14:08
The cycles caused by XState are indeed solved in `4.13.0`.

Cycles caused elsewhere need to be handled somehow.

**Comment by Blacktiger** [comment] 2020-10-02 14:29
The cycle issue wasn't fixed in my case on 4.13.0 (though I did find a workaround for the issue).

**Comment by n-dvo-tech** [comment] 2020-11-09 17:38
I'm on v4.13.0 of xstate and started having a circular reference issue when using @xstate/inspect (v0.2.0). The issue happens when I have another window object as part of the context for a machine. Typically I'm using a port for channel messaging but for backwards compatibility in certain cases I use the source window object from MessageEvent. I know I can slim down the window object I'm adding to the context to avoid the error to just the properties I really need but that's how the error was occurring for me.

**Comment by jawond** [comment] 2020-11-18 09:41
I'm also on v4.13.0 and I was passing a hierarchical data structure in an event payload and getting "TypeError: cyclic object value" until I commented out the call to inspect.

**Comment by joshferrell** [comment] 2020-12-05 20:53
On xstate 4.14.0 and inspect 0.2.0. Getting the error for certain machines, but not all. Error only occurs when inspecting the machine.

**Closed** 2020-12-12 21:51 UTC
Labels: bug, 🔎 @xstate/inspect, 🖼 @xstate/viz
