### ISSUE TITLE
@xstate/inspect waiting for connection in Svelte app

### ISSUE THREAD

**Issue by csell5** [davidkpiano/xstate#1617] opened 2020-11-06 20:41 UTC
**Description**
The recent 0.2.0 update for @xstate/inspect fixed #1583 but now the connection isn't connecting https://statecharts.io/inspect.

**Expected Result**
Svelte app to connect to the @xstate/inspect tooling

**Actual Result**
`Waiting for Connection` with no errors in the logs.

**Reproduction**
I've created a simple svelte app and state machine here: https://github.com/csell5/xstate-inspect-debug.

* Node 12.18.2 or higher.
* `npm i`
* `npm run dev` to start

**Additional context**

Right now the call to inspect is in `main.js`. I've tried calling it in the app script, in the app `script context=module` all with the same results. window is also defined at those points as well.

Unfortunately I'm a bit of a loss as to how to debug further.

**Comment by davidkpiano** [comment] 2020-11-06 20:45
Was it working before? You want to make sure that the `inspect(...)` call is run before any other `useMachine(...)` code.

**Comment by csell5** [comment] 2020-11-06 22:06
Honestly I've never gotten it to work and this is the first time where I was able to get past the rollup compile step. 

I was running inspect right at the start of the app so long before useMachine was ever called.

**Comment by tillbaks** [comment] 2020-11-09 12:40
I had this problem for some of my machines that I create before any components are mounted.To fix it I have moved the xstate-inspect call out of the svelte bundle into a separate js file and include it before the svelte bundle in index.html.

**Comment by csell5** [comment] 2020-11-09 15:52
@tillbaks interesting.. I did update the example but I'm still not seeing it work. Essentially created a separate bundle just for inspect and then pull that in before the main bundle.

https://github.com/csell5/xstate-inspect-debug/pull/1

Clearly I'm missing something somewhere.

**Comment by tillbaks** [comment] 2020-11-10 09:13
That is exactly what I'm doing. I tried your repo now and can't get it to connect either. Now I wonder how I got it working in my app...

**Comment by csell5** [comment] 2020-11-16 14:20
@davidkpiano any thoughts? I'd love to help debug more but I could use a little help as how I could help.

**Comment by Andarist** [comment] 2020-11-16 15:22
@csell5 One of the problems you have there is that you have effectively disabled devtools with this:
https://github.com/csell5/xstate-inspect-debug/blob/999a1bd7fc45ae9eb114184af715f62c37c3f169/rollup.config.js#L54
You should replace with `"development"` when, well, developing 😅 

However, this doesn't resolve the issue completely. No message event from the opened page is received and thus [`xstate.inspecting`](https://github.com/davidkpiano/xstate/blob/6c1ffa17098a86b4646bcf2f2ad3305856a8dec9/packages/xstate-inspect/src/index.ts#L112) event is never received by the inspect service.

**Comment by csell5** [comment] 2020-11-16 16:24
OMFG you have to be kidding me. How in the world did I bork that up. Yea that is a huge oversight on my part. I sincerely apologize about that.

I'm not sure I follow this point though:
```

**Comment by Andarist** [comment] 2020-11-16 16:33
> I'm seeing things working although it appears I have to refresh between pages/components which has different machines on them. I wasn't sure if that was a problem of mine or what you're referring too.

Can't right now comment on the latter but after fixing that replace problem I still couldn't make it work because no message event was delivered to me from the opened page but it seems that maybe this was an issue with my environment and not a general issue. I will have to investigate this later on my own.

**Comment by shedali** [comment] 2020-12-24 18:53
same issue with barebones snowpack app,  [repro](https://github.com/shedali/xstate-inspect-snowpack)

**Comment by kyrianda** [comment] 2021-02-27 22:42
I created a new svelte app today and had no problems to getting inspect work. The repo can be found here [svelte-state-inspect-plantuml](https://github.com/kyrianda/svelte-xstate-inspect-plantuml).

**Comment by davidkpiano** [comment] 2021-05-21 20:30
Closing as this cannot be reproduced.

**Closed by davidkpiano** 2021-05-21 20:30 UTC
Labels: documentation, 🔎 @xstate/inspect
