### ISSUE TITLE
Tags are not set on all updates when having an async callback service

### ISSUE THREAD

**Issue by mr-bjerre** [davidkpiano/xstate#2172] opened 2021-05-04 10:01 UTC
**Description**
I have a machine where I invoke a callback service

```javascript
() => async (callback, onReceive) => ...
```

Having a service like above causes the machine to emit an event where the tags from the state are not carried over.

**Expected Result**

I'd expect the tags to always be present when in a state with tags.

**Actual Result**

The tags are not always present

**Reproduction**

Here is [CSB](https://codesandbox.io/s/strange-buck-0zmew?file=/src/index.js) that showcases the issue.

The console outputs 
```
isBooting: true
state:  booting 
isBooting: false
state:  booting 
```

If I remove `async` keyword from the service then I get 
```
isBooting: true
state:  booting 
```

**Additional context**
`XState 4.19.0`

**Comment by Andarist** [comment] 2021-05-04 11:31
I already know where the problem is - expect this to be fixed in the evening.

**Closed** 2021-05-05 00:40 UTC
