### ISSUE TITLE
XState Viz crashing

### ISSUE THREAD

**Issue by Iskereat** [davidkpiano/xstate#1001] opened 2020-02-14 03:22 UTC
**Description**
When i try the paste code below it crashes and the screen goes white.

I get a "Uncaught TypeError: Cannot read property 'indexOf' of undefined" error.

**Reproduction**

post below xstate.
It seems to be something with the actions?
I removed them and it worked fine.
I dont think the problem is on my end (im a newb so maybe idk)
```

const questMachine = Machine({
    id: 'quest',
    initial: 'posted',
    context: { 
        creator: 'hello2',
        receiver: 'world2'
    },
    states: {
        posted: {
            on: {
                PICKEDUP: 'active'
            },
            entry: {
                actions: 'addReceiverID'
            }
        },
        active: {
            on: {
                TURNIN: 'turnedin',
            },
            initial: 'unstarred',
            states: {
                unstarred: {
                    on: {
                        STAR: 'starred'
                    }
                },
                starred: {
                    on: {
                        UNSTAR: 'unstarred'
                    }
                }
            },
            entry: {
                actions: 'addCreatorID'
            }
        },
        turnedin: {
            on: {
                ACCEPTED: 'completed'
            }
        },
        completed: {
            type: 'final'
        },
    }

},
{
    actions: {
        addCreatorID: assign({
            creator: 'hello'
        }),
        addReceiverID: assign({
            receiver: 'world'
        })
    }
})

```

**Comment by marceloadsj** [comment] 2020-02-20 10:31
I think your **entry** keys should be a string or an array of strings.

**Comment by ivorpad** [comment] 2020-02-27 22:10
The problem is not what's wrong in this code, the problem is that while I was making a state machine the XState Viz crashed and I lost all my progress. I know it's my fault but still is worth noting it.

**Comment by marceloadsj** [comment] 2020-02-28 00:42
Yep, makes sense. Of course we can have problems on the code of the machine itself, but the viz shouldn't break because of this!

I just pointed the problem there to help to actually fiz that specific issue on the machine config.

**Comment by davidkpiano** [comment] 2020-03-13 19:18
Closing - this will be fixed soon and issues with XState Viz (the current visualizer) should be moved to github.com/statecharts/xstate-viz

**Closed by davidkpiano** 2020-03-13 19:18 UTC
Labels: bug
