### ISSUE TITLE
Super Quick Example fails to run on Node v14

### ISSUE THREAD

**Issue by EulerTourist** [davidkpiano/xstate#1168] opened 2020-05-01 00:06 UTC
**Description**
Super quick example fails to run

**Expected Result**

**Actual Result**
import { createMachine, interpret } from 'xstate';
                                          ^^^^^^^^^
SyntaxError: The requested module 'xstate' does not provide an export named 'interpret'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
steve@Steves-MBP src % node -v
v14.0.0

**Comment by davidkpiano** [comment] 2020-05-01 01:20
cc. @Andarist Is this an ESM issue?

**Comment by EulerTourist** [comment] 2020-05-01 06:16
I am able to get it going for now with:

    import fsm from 'xstate';
    const lightMachine = fsm.createMachine(config);

    //also as service
    const lightService = fsm.interpret(lightMachine);

**Comment by Andarist** [comment] 2020-05-01 22:11
Duplicate of https://github.com/davidkpiano/xstate/issues/963

> @Andarist Is this an ESM issue?

Yes. We currently don't provide enough information for node (through package.json) for it to be able to load our ESM files. The issue is not so simple as it might look like though, comes with some caveats and at this point in time changing it for v4 would be a breaking change for every ESM consumer in node as they would have to change all import statements for XState. The support for modules in node is also still considered as experimental so I don't really think that we should jump into fixing this straight away (especially that - as mentioned - this only looks trivial, we also don't know yet how bundlers will handle conditional exports which are expected to be handled by them)

**Comment by davidkpiano** [comment] 2020-05-19 23:38
Closing as duplicate

**Closed by davidkpiano** 2020-05-19 23:38 UTC
Labels: bug, duplicate
