### ISSUE TITLE
machine instance type is never

### ISSUE THREAD

**Issue by Hydrock** [davidkpiano/xstate#1184] opened 2020-05-12 11:17 UTC
**Description**
when using the machine after the operator or is defined as never
this problem is appear in xstate@4.7.0

**Expected Result**
this result on 4.7.1
![image](https://user-images.githubusercontent.com/20814779/81677706-d7b22d00-9459-11ea-802d-3f623dcd8bdf.png)

**Actual Result**
this result on 4.6.7
![image](https://user-images.githubusercontent.com/20814779/81677488-aa657f00-9459-11ea-9163-3cfd82ef489f.png)

**Comment by davidkpiano** [comment] 2020-05-12 12:35
Please share a CodeSandbox example and ensure you're using the latest TypeScript version.

**Comment by CodingDive** [comment] 2020-05-12 13:41
Duplicate of https://github.com/davidkpiano/xstate/issues/1142 and https://github.com/davidkpiano/xstate/issues/947

One workaround is to assign the state.matches return value into a variable. State only becomes never when returning early.

E.g 
`const isNotSelected = !state.matches("selected");` and then using the variable in your conditionals should make it work.

**Comment by davidkpiano** [comment] 2020-05-19 23:37
Fixed in #1189

**Closed by davidkpiano** 2020-05-19 23:37 UTC
Labels: bug, duplicate, has workaround
